var T={
 tr:{brand:"Rusya Rehberi",sights:"GÖRÜLECEK YERLER",food:"NEREDE YEMEK YENİR",cityDesc:{moscow:"Rusya'nın başkenti. Haritadaki noktalara veya kartlara dokunun.",spb:"Rusya'nın kültür başkenti. Haritadaki noktalara veya kartlara dokunun."},cat:{must:"Mutlaka",park:"Park",museum:"Müze",shop:"AVM",modern:"Modern",food:"Restoran"},time:"Süre",price:"Kişi başı",btnMap:"Google Haritalar",btnPhoto:"Tüm fotoğraflar",why:"Neden?",schNote:"Harita yüklenemedi. Kartlara dokunarak bilgilere ulaşın."},
 ru:{brand:"Гид по России",sights:"ДОСТОПРИМЕЧАТЕЛЬНОСТИ",food:"ГДЕ ПОЕСТЬ",cityDesc:{moscow:"Столица России. Нажмите на точки на карте или на карточки.",spb:"Культурная столица России. Нажмите на точки на карте или на карточки."},cat:{must:"Обязательно",park:"Парк",museum:"Музей",shop:"ТЦ",modern:"Современное",food:"Ресторан"},time:"Время",price:"На человека",btnMap:"Google Maps",btnPhoto:"Все фото",why:"Почему?",schNote:"Карта не загрузилась. Нажмите на карточки для информации."}
};


var P={
 kremlin:["photos/kremlin_1.jpg","photos/kremlin_3.jpg","photos/kremlin_4.jpg","photos/kremlin_5.jpg","photos/kremlin_6.jpg","photos/kremlin_2.jpg"],
 redsquare:["photos/redsquare_1.jpg","photos/redsquare_2.jpg","photos/redsquare_3.jpg"],
 basil:["photos/basil_1.jpg","photos/basil_2.jpg","photos/basil_3.jpg","photos/basil_4.jpg"],
 gum:["photos/gum_4.jpg","photos/gum_1.jpg","photos/gum_2.jpg","photos/gum_3.jpg"],
 zaryadye:["photos/zaryadye_1.jpg","photos/zaryadye_2.jpg"],
 tretyakov:["photos/tretyakov_1.jpg","photos/tretyakov_2.jpg","photos/tretyakov_3.jpg"],
 bolshoi:["photos/bolshoi_4.jpg","photos/bolshoi_1.jpg","photos/bolshoi_5.jpg","photos/bolshoi_2.jpg","photos/bolshoi_3.jpg"],
 city:["photos/city_1.jpg","photos/city_2.jpg","photos/city_3.jpg","photos/city_4.jpg"],
 sparrow:["photos/sparrow_2.jpg","photos/sparrow_1.jpg","photos/sparrow_5.jpg","photos/sparrow_3.jpg","photos/sparrow_4.jpg","photos/sparrow_6.jpg"],
 saviour:["photos/saviour_1.jpg","photos/saviour_4.jpg","photos/saviour_2.jpg","photos/saviour_3.jpg","photos/saviour_5.jpg"],
 arbat:["photos/arbat_1.jpg","photos/arbat_2.jpg","photos/arbat_3.jpg"],
 food_pushkin:["photos/food_pushkin_1.jpg","photos/food_pushkin_2.jpg"],
 food_sakhalin:["photos/сахалин1.jpg","photos/сахалин2.jpg","photos/сахалин3.jpg","photos/сахалин4.jpg","photos/сахалин5.jpg"],
 food_expedition:["photos/экспедиция1.jpg","photos/экспедиция2.jpg","photos/экспедиция3.jpg"],
 hermitage:["photos/hermitage_1.jpg","photos/hermitage_2.jpg","photos/hermitage_3.jpg","photos/hermitage_4.jpg","photos/hermitage_5.jpg","photos/hermitage_6.jpg","photos/hermitage_7.jpg","photos/hermitage_8.jpg","photos/hermitage_9.jpg","photos/hermitage_10.jpg"],
 palace_sq:["photos/palace_sq_3.jpg","photos/palace_sq_1.jpg","photos/palace_sq_2.jpg"],
 isaac:["photos/isaac_1.jpg","photos/isaac_4.jpg","photos/isaac_3.jpg","photos/isaac_5.jpg","photos/isaac_6.jpg","photos/isaac_7.jpg","photos/isaac_8.jpg","photos/isaac_2.jpg"],
 blood:["photos/blood_main.jpg","photos/blood_2.jpg","photos/blood_1.jpg","photos/blood_3.jpg","photos/blood_4.jpg","photos/blood_5.jpg","photos/blood_6.jpg"],
 nevsky:["photos/nevsk-e1592493878183.jpg","photos/nevsky_prospekt.jpg","photos/zaglavnaya-nevskiy-prospekt.jpg","photos/nevsky4.jpg"],
 petropavlovsk:["photos/RUS-2016-Aerial-SPB-Peter_and_Paul_Fortress_02.jpg","photos/petropavlovka1.jpg","photos/petropavlovka2.jpg","photos/RUS-2016-Aerial-SPB-Military_Historical_Museum_of_Artillery.jpg","photos/petropavlovka3.jpg"],
 peterhof:["photos/Grand_Cascade_of_Peterhof_01.jpg","photos/Peterhof_Fountains_01_-_Big_Cascade_02.jpg","photos/Petergof_Alexander_Nevsky_chapel_2009-08_1249234328.jpg"],
 tsarskoe:["photos/Catherine_Palace_in_Tsarskoe_Selo.jpg","photos/tsarskoe1.jpeg","photos/2002-11-15_071b_Puschkin_Bernsteinzimmer.jpg","photos/Pushkin_Catherine_Palace_Interiors_02.jpg","photos/tsarskoe2.jpg","photos/tsarskoe3.jpg","photos/tsarskoe4.jpg","photos/Pushkin_Catherine_Palace_Interiors_05.jpg","photos/FR_Carskie_Siolo,_palac,_in,_2013.08.10,_fot._I._Nowicka_(3)_corr.jpg"],
 strelka:["photos/Spb_06-2017_img01_Spit_of_Vasilievsky_Island.jpg","photos/St_petersburg_4.jpg","photos/День_города_2011.jpeg"],
 bridges:["photos/разводные_мосты.jpg","photos/мосты1.png"],
 food_palkin:["photos/Палкинъ1.jpg","photos/палкин1 .webp","photos/палкин2.webp","photos/палкин3.webp","photos/палкин4.webp"],
 food_orangerie:["photos/оранжерея1.jpg","photos/оранжерея2.jpg","photos/оранжерея3.jpg","photos/оранжерея4.jpg"],
 food_leth:["photos/44ff4096c9fbabcd04cd169a227c032a.jpg","photos/e977d9d7199e8cc9a6c3d18f2b4768c4.jpg","photos/883b66cd96a759284d9f0b82561d2178_w1230_h820--no-cut.webp","photos/Leth2-1-scaled-e1689194596763.webp"],
 dream_island:["photos/Остров_Мечты1.jpeg","photos/Остров_Мечты2.jpg","photos/Остров_Мечты3.webp","photos/mechta-1.jpg"],
 krymskaya:["photos/Крымская_набережная_Музеон1.jpg","photos/qoh3mdqcj5z073i9ffg5c62vgt0vc1di.jpg","photos/o37io5kyx72kuzjlqudylrwybu7qhwok.jpg"],
 shukhov:["photos/шуховская_башня2.webp","photos/шуховская_башня.jpg","photos/moskva-shuhovskaya-bashnya-02.jpg","photos/moskva-shuhovskaya-bashnya-19.jpg"],
 izmaylovo:["photos/izmajlovskogo-kremlja1.jpg","photos/izmajlovskogo-kremlja2-1.jpg","photos/izmajlovskogo-kremlja3-1.jpg","photos/izmajlovskogo-kremlja4.jpg","photos/izmajlovskogo-kremlja6.jpg"],
 dommusyki:["photos/дом_музыки1.jpg","photos/дом_музыки2.jpg","photos/dom-myziki.jpg.jpeg","photos/дом_музыки4.jpeg"],
 ostankino:["photos/ostankinskaya-bashnya2.jpg","photos/ostankinskaya-bashnya1.jpg","photos/останкиская.jpg","photos/останкинская_.jpg","photos/останкин.jpg","photos/restoran_7_nebo_v_ostankino_7.jpg"],
 bunker42:["photos/bunker42_stlina3.jpg","photos/bunker42_stlina.jpg","photos/bunker42_stlina14.jpg","photos/bunker42_stlina18.jpg","photos/bunker42_stlina21.jpg"],
 gorky:["photos/Moscow_Gorky_Park_colonnades_viewpoint_08-2016_img1.jpg","photos/Moscow_Gorky_Park_View_from_Crimea_Bridge.jpg","photos/Moscow_Gorky_Park_main_portal_08-2016_img1.jpg"],
 aptekarsky:["photos/aptekarsky1.jpg","photos/aptekarsky2.jpg","photos/aptekarsky3.jpg","photos/aptekarsky4.jpg"]
};

var DATA={
 moscow:{center:[55.751,37.618],zoom:12,name:{tr:"Moskova",ru:"Москва"},
  svgRiver:"M -20 250 C 120 230 200 300 320 320 C 440 340 520 300 640 340 C 720 365 780 340 860 360",
  places:[
  {cat:"must",x:430,y:300,lat:55.7520,lng:37.6175,imgs:P.kremlin,metro:{tr:"Biblioteka im. Lenina",ru:"Библиотека им. Ленина"},time:"2–4 s",name:{tr:"Kremlin",ru:"Кремль"},desc:{tr:"Moskova'nın tarihi ve siyasi merkezi.",ru:"Исторический и политический центр Москвы."},why:{tr:["Rus tarihinin kalbi","Muhteşem mimari","UNESCO Dünya Mirası"],ru:["Сердце русской истории","Великолепная архитектура","Наследие ЮНЕСКО"]}},
  {cat:"must",x:455,y:285,lat:55.7539,lng:37.6208,imgs:P.redsquare,metro:{tr:"Okhotny Ryad",ru:"Охотный ряд"},time:"1–2 s",name:{tr:"Kızıl Meydan",ru:"Красная площадь"},desc:{tr:"Rusya'nın en ünlü meydanı ve Moskova'nın simgesi.",ru:"Самая известная площадь России и символ Москвы."},why:{tr:["Moskova'nın simgesi","Fotoğraf için mükemmel","Şehrin merkezi"],ru:["Символ Москвы","Идеально для фото","Центр города"]}},
  {cat:"must",x:472,y:300,lat:55.7525,lng:37.6231,imgs:P.basil,metro:{tr:"Okhotny Ryad",ru:"Охотный ряд"},time:"1 s",name:{tr:"Aziz Vasili Katedrali",ru:"Храм Василия Блаженного"},desc:{tr:"Renkli soğan kubbeleriyle dünyanın en tanınmış yapılarından biri.",ru:"Один из самых узнаваемых храмов мира с разноцветными куполами."},why:{tr:["Rusya'nın en ikonik yapısı","Eşsiz mimari","Harika fotoğraf"],ru:["Самое узнаваемое здание России","Уникальная архитектура","Отличное фото"]}},
  {cat:"shop",x:460,y:272,lat:55.7547,lng:37.6213,imgs:P.gum,metro:{tr:"Okhotny Ryad",ru:"Охотный ряд"},time:"1–2 s",name:{tr:"GUM (Alışveriş Merkezi)",ru:"ГУМ"},desc:{tr:"Kızıl Meydan'ın yanındaki tarihi alışveriş merkezi.",ru:"Исторический торговый центр рядом с Красной площадью."},why:{tr:["Tarihi mimari","Fotoğraf için ideal","Merkezi konum"],ru:["Историческая архитектура","Идеально для фото","Центр"]}},
  {cat:"park",x:495,y:310,lat:55.7514,lng:37.6283,imgs:P.zaryadye,metro:{tr:"Kitay-Gorod",ru:"Китай-город"},time:"1–2 s",name:{tr:"Zaryadye Parkı",ru:"Парк Зарядье"},desc:{tr:"Kremlin'e yürüme mesafesinde Moskova'nın en modern parkı.",ru:"Самый современный парк Москвы рядом с Кремлём."},why:{tr:["En güzel manzara","Modern mimari","Gün batımı için harika"],ru:["Лучший вид на город","Современная архитектура","Отлично на закате"]}},
  {cat:"museum",x:430,y:355,lat:55.7415,lng:37.6208,imgs:P.tretyakov,metro:{tr:"Tretyakovskaya",ru:"Третьяковская"},time:"2–3 s",name:{tr:"Tretyakov Galerisi",ru:"Третьяковская галерея"},desc:{tr:"Rus resim sanatının en büyük müzesi.",ru:"Крупнейший музей русской живописи."},why:{tr:["Rus sanatının hazinesi","Dünyaca ünlü tablolar","Kültürel zenginlik"],ru:["Сокровищница русского искусства","Известные картины","Культурное богатство"]}},
  {cat:"must",x:445,y:255,lat:55.7601,lng:37.6186,imgs:P.bolshoi,metro:{tr:"Teatralnaya",ru:"Театральная"},time:"gösteri",name:{tr:"Bolşoy Tiyatrosu",ru:"Большой театр"},desc:{tr:"Dünyanın en ünlü bale ve opera sahnelerinden biri.",ru:"Одна из самых знаменитых сцен балета и оперы в мире."},why:{tr:["Dünya çapında bale & opera","Görkemli mimari","Eşsiz deneyim"],ru:["Балет и опера мирового уровня","Великолепная архитектура","Незабываемо"]}},
  {cat:"modern",x:250,y:250,lat:55.7473,lng:37.5377,imgs:P.city,metro:{tr:"Vystavochnaya",ru:"Выставочная"},time:"1–2 s",name:{tr:"Moskova City",ru:"Москва-Сити"},desc:{tr:"Modern Moskova'nın simgesi gökdelen bölgesi.",ru:"Район небоскрёбов — символ современной Москвы."},why:{tr:["En yüksek manzara","Modern mimari","Restoran & gözlem"],ru:["Самый высокий вид","Современная архитектура","Рестораны и смотровые"]}},
  {cat:"park",x:400,y:380,lat:55.7282,lng:37.6014,imgs:P.gorky,metro:{tr:"Park Kultury",ru:"Парк культуры"},time:"2 s",name:{tr:"Gorki Parkı",ru:"Парк Горького"},desc:{tr:"Moskova Nehri kıyısındaki ünlü dinlenme parkı.",ru:"Знаменитый парк на берегу Москвы-реки."},why:{tr:["Yerel hayat","Nehir kıyısı","Her mevsim aktivite"],ru:["Местная жизнь","Берег реки","Активности круглый год"]}},
  {cat:"must",x:300,y:430,lat:55.7103,lng:37.5419,imgs:P.sparrow,metro:{tr:"Vorobyovy Gory",ru:"Воробьёвы горы"},time:"1–2 s",name:{tr:"Serçe Tepeleri & MGU",ru:"Воробьёвы горы и МГУ"},desc:{tr:"Şehrin en ünlü gözlem terası.",ru:"Самая известная смотровая площадка города."},why:{tr:["Panoramik manzara","Görkemli üniversite","Harika fotoğraf"],ru:["Панорама города","Грандиозное здание","Отличное фото"]}},
  {cat:"must",x:390,y:335,lat:55.7446,lng:37.6055,imgs:P.saviour,metro:{tr:"Kropotkinskaya",ru:"Кропоткинская"},time:"1 s",name:{tr:"Kurtarıcı İsa Katedrali",ru:"Храм Христа Спасителя"},desc:{tr:"Rusya'nın en büyük Ortodoks katedrali.",ru:"Крупнейший православный храм России."},why:{tr:["En büyük katedral","Altın kubbeler","Güzel manzara"],ru:["Крупнейший храм России","Золотые купола","Красивый вид"]}},
  {cat:"shop",x:360,y:290,lat:55.7497,lng:37.5871,imgs:P.arbat,metro:{tr:"Arbatskaya",ru:"Арбатская"},time:"1–2 s",name:{tr:"Eski Arbat Caddesi",ru:"Старый Арбат"},desc:{tr:"Moskova'nın en ünlü yaya caddesi.",ru:"Самая известная пешеходная улица Москвы."},why:{tr:["Canlı atmosfer","Hediyelik eşya","Kafeler & sanatçılar"],ru:["Живая атмосфера","Сувениры","Кафе и художники"]}},
  {cat:"modern",x:500,y:430,lat:55.6727,lng:37.6521,imgs:P.dream_island,metro:{tr:"Tehnoparka",ru:"Технопарк"},time:"3–5 s",name:{tr:"Hayal Adası (Dream Island)",ru:"Остров Мечты"},desc:{tr:"Avrupa'nın en büyük kapalı eğlence parkı.",ru:"Крупнейший крытый тематический парк Европы."},why:{tr:["Avrupa'nın en büyük kapalı parkı","Her mevsim açık","Aileler için mükemmel"],ru:["Крупнейший крытый парк Европы","Открыт круглый год","Идеально для семей"]}},
  {cat:"park",x:390,y:360,lat:55.7360,lng:37.6027,imgs:P.krymskaya,metro:{tr:"Park Kultury / Oktabrskaya",ru:"Парк культуры / Октябрьская"},time:"1–2 s",name:{tr:"Kırım Sahil Yolu ve Müzeon",ru:"Крымская набережная и Музеон"},desc:{tr:"Moskova Nehri kıyısında 900 metrelik yaya promenadı.",ru:"900-метровый бульвар вдоль Москвы-реки."},why:{tr:["Açık hava heykel müzesi","Nehir kenarı yürüyüşü","Kafeler & sanat"],ru:["Музей скульптуры под небом","Прогулка вдоль реки","Кафе и искусство"]}},
  {cat:"modern",x:430,y:390,lat:55.7166,lng:37.6080,imgs:P.shukhov,metro:{tr:"Şabolovskaya",ru:"Шаболовская"},time:"30 dak",name:{tr:"Şuhov Kulesi",ru:"Шуховская башня"},desc:{tr:"1922 yılında inşa edilen 160 metrelik çelik ağ kafes kulesi.",ru:"Стальная гиперболоидная башня высотой 160 м (1922)."},why:{tr:["Dünya mühendislik şaheseri","Sovyet TV simgesi","Eşsiz tasarım"],ru:["Шедевр мировой инженерии","Символ советского TV","Уникальный гиперболоид"]}},
  {cat:"modern",x:500,y:200,lat:55.8197,lng:37.6113,imgs:P.ostankino,metro:{tr:"VDNKh",ru:"ВДНХ"},time:"2 s",name:{tr:"Ostankino Kulesi",ru:"Останкинская башня"},desc:{tr:"540 metre yüksekliğiyle Avrupa'nın en yüksek yapısı.",ru:"540 м — самое высокое сооружение Европы."},why:{tr:["Avrupa'nın en yüksek yapısı","360° Moskova panoraması","Cam tabanlı seyir terası"],ru:["Самое высокое в Европе","Панорама 360°","Стеклянный пол на 340 м"]}},
  {cat:"must",x:640,y:280,lat:55.7900,lng:37.7480,imgs:P.izmaylovo,metro:{tr:"Partizanskaya",ru:"Партизанская"},time:"2–3 s",name:{tr:"İzmaylovo Kreml",ru:"Измайловский Кремль"},desc:{tr:"Rengarenk eski Rus mimarisi kültür kompleksi.",ru:"Яркий комплекс в стиле допетровской Руси."},why:{tr:["Eski Rusya atmosferi","Benzersiz renkli mimari","El sanatları & müzeler"],ru:["Атмосфера допетровской Руси","Уникальная яркая архитектура","Ремёсла и музеи"]}},
  {cat:"museum",x:490,y:335,lat:55.7440,lng:37.6440,imgs:P.bunker42,metro:{tr:"Taganskaya",ru:"Таганская"},time:"2 s",name:{tr:"Sığınak-42 (Soğuk Savaş Müzesi)",ru:"Бункер-42 (Музей Холодной войны)"},desc:{tr:"Yüzeyin 65 metre altında gizli Sovyet sığınağı.",ru:"Секретный советский бункер глубиной 65 метров."},why:{tr:["65 metre derinlikte gerçek sığınak","Soğuk Savaş tarihi","Tüyler ürpertici deneyim"],ru:["Настоящий бункер на 65 м","История Холодной войны","Уникальный опыт"]}},
  {cat:"museum",x:450,y:175,lat:55.7760,lng:37.6423,imgs:P.dommusyki,metro:{tr:"Paveletskaya",ru:"Павелецкая"},time:"gösteri",name:{tr:"Uluslararası Müzik Evi",ru:"Московский международный дом музыки"},desc:{tr:"Moskova'nın en prestijli konser kompleksi.",ru:"Престижнейший концертный комплекс Москвы."},why:{tr:["Dünyanın en büyük orglarından","Prestijli konser salonu","Nehir kenarı mimari"],ru:["Один из крупнейших органов мира","Престижный концертный зал","Архитектура на реке"]}},
  {cat:"park",x:470,y:220,lat:55.7762,lng:37.6344,imgs:P.aptekarsky,metro:{tr:"Prospekt Mira",ru:"Проспект Мира"},time:"1–2 s",name:{tr:"Eczacı Bahçesi (Aptekarsky Ogorod)",ru:"Аптекарский огород"},desc:{tr:"I. Petro'nun 1706 yılında kurduğu Rusya'nın en eski botanik bahçesi.",ru:"Старейший ботанический сад России, основанный Петром I в 1706 году."},why:{tr:["1706'dan beri en eski bahçe","Tropikal seralar","Şehir merkezinde yeşil alan"],ru:["Старейший сад России","Тропические оранжереи","Зелёный оазис в центре"]}}
  ],
  food:[
  {cat:"food",x:430,y:230,lat:55.7649,lng:37.6049,imgs:P.food_pushkin,metro:{tr:"Tverskaya",ru:"Тверская"},price:{tr:"≈ 3000–4000 ₽",ru:"≈ 3000–4000 ₽"},name:{tr:"Kafe Puşkin",ru:"Кафе Пушкинъ"},desc:{tr:"18. yüzyıldan kalma bir konakta efsanevi restoran.",ru:"Легендарный ресторан в особняке XVIII века."},why:{tr:["Eşsiz tarihi iç mekân","Eski Rus mutfağı","Şehrin simge restoranı"],ru:["Уникальный исторический интерьер","Старинная русская кухня","Знаковый ресторан"]}},
  {cat:"food",x:620,y:250,lat:55.7558,lng:37.6395,imgs:P.food_expedition,metro:{tr:"Kitay-Gorod",ru:"Китай-город"},price:{tr:"≈ 2500–3500 ₽",ru:"≈ 2500–3500 ₽"},name:{tr:"Ekspeditsiya (Kuzey Mutfağı)",ru:"Экспедиция (Северная кухня)"},desc:{tr:"Rusya'nın Uzak Kuzey mutfağı. Salonun ortasında gerçek bir helikopter durur.",ru:"Кухня Крайнего Севера. В центре зала стоит настоящий вертолёт."},why:{tr:["Salonda gerçek helikopter","Kuzey'in eşsiz lezzetleri","Sıra dışı deneyim"],ru:["Настоящий вертолёт в зале","Уникальная северная кухня","Необычный опыт"]}},
  {cat:"food",x:255,y:245,lat:55.7494,lng:37.5392,imgs:P.food_sakhalin,metro:{tr:"Vystavochnaya",ru:"Выставочная"},price:{tr:"≈ 4000–7000 ₽",ru:"≈ 4000–7000 ₽"},name:{tr:"Sahalin (Panoramik Restoran)",ru:"Сахалин (Панорамный ресторан)"},desc:{tr:"Gökdelenlerin yüksek katlarında panoramik manzaralı restoran.",ru:"Ресторан на верхних этажах небоскрёба с панорамным видом."},why:{tr:["Şehrin en yüksek manzarası","Premium mutfak","Gün batımı manzarası"],ru:["Самый высокий вид","Премиум-кухня","Вид на закат"]}}
 ]},
 spb:{center:[59.937,30.32],zoom:12,name:{tr:"St. Petersburg",ru:"Санкт-Петербург"},
  svgRiver:"M -20 200 C 140 210 240 180 340 230 C 420 270 470 250 540 210 C 620 165 720 200 860 180 M 340 230 C 360 320 420 400 520 470",
  places:[
  {cat:"museum",x:430,y:235,lat:59.9398,lng:30.3146,imgs:P.hermitage,metro:{tr:"Admiralteyskaya",ru:"Адмиралтейская"},time:"3–5 s",name:{tr:"Ermitaj & Kışlık Saray",ru:"Эрмитаж (Зимний дворец)"},desc:{tr:"Dünyanın en büyük müzelerinden biri ve eski çarların Kışlık Sarayı.",ru:"Один из крупнейших музеев мира и бывший Зимний дворец."},why:{tr:["En büyük müzelerden","İmparatorluk sarayı","Paha biçilemez koleksiyon"],ru:["Крупнейший музей мира","Императорский дворец","Бесценная коллекция"]}},
  {cat:"must",x:445,y:248,lat:59.9386,lng:30.3158,imgs:P.palace_sq,metro:{tr:"Admiralteyskaya",ru:"Адмиралтейская"},time:"1 s",name:{tr:"Saray Meydanı",ru:"Дворцовая площадь"},desc:{tr:"Şehrin ana meydanı; Kışlık Saray ile çevrili.",ru:"Главная площадь города перед Зимним дворцом."},why:{tr:["Şehrin kalbi","Görkemli mimari","Fotoğraf için mükemmel"],ru:["Сердце города","Торжественная архитектура","Идеально для фото"]}},
  {cat:"must",x:420,y:275,lat:59.9341,lng:30.3061,imgs:P.isaac,metro:{tr:"Admiralteyskaya",ru:"Адмиралтейская"},time:"1–2 s",name:{tr:"Aziz Isaak Katedrali",ru:"Исаакиевский собор"},desc:{tr:"Devasa altın kubbesiyle şehrin en büyük katedrali.",ru:"Крупнейший собор города с золотым куполом."},why:{tr:["Devasa altın kubbe","360° manzara","Görkemli iç mekân"],ru:["Огромный купол","Панорама 360°","Роскошный интерьер"]}},
  {cat:"must",x:470,y:215,lat:59.9403,lng:30.3286,imgs:P.blood,metro:{tr:"Nevsky Prospekt",ru:"Невский проспект"},time:"1 s",name:{tr:"Kanlı Kilise",ru:"Спас на Крови"},desc:{tr:"Renkli mozaik kubbeleriyle çarpıcı bir kilise.",ru:"Яркая церковь с мозаичными куполами."},why:{tr:["Eşsiz mozaik","En güzel kilise","Harika fotoğraf"],ru:["Уникальная мозаика","Красивейшая церковь","Отличное фото"]}},
  {cat:"shop",x:500,y:250,lat:59.9333,lng:30.3304,imgs:P.nevsky,metro:{tr:"Nevsky Prospekt",ru:"Невский проспект"},time:"2–3 s",name:{tr:"Nevski Bulvarı",ru:"Невский проспект"},desc:{tr:"Şehrin ana caddesi. Tarihi binalar ve Kazan Katedrali.",ru:"Главная улица города. Исторические здания и Казанский собор."},why:{tr:["Ana cadde","Tarihi binalar","Alışveriş"],ru:["Главная улица","Исторические здания","Шопинг"]}},
  {cat:"must",x:405,y:200,lat:59.9500,lng:30.3167,imgs:P.petropavlovsk,metro:{tr:"Gorkovskaya",ru:"Горьковская"},time:"2 s",name:{tr:"Petropavlovsk Kalesi",ru:"Петропавловская крепость"},desc:{tr:"Şehrin kurulduğu nokta. Çarların gömülü olduğu katedral.",ru:"Место основания города. Собор-усыпальница царей."},why:{tr:["Şehrin doğduğu yer","Çarların mezarı","Güzel nehir manzarası"],ru:["Колыбель города","Усыпальница царей","Красивый вид на реку"]}},
  {cat:"park",x:120,y:480,lat:59.8847,lng:29.9083,imgs:P.peterhof,metro:{tr:"(Şehir dışı — tren/tekne)",ru:"(За городом — электричка/катер)"},time:"yarım gün",name:{tr:"Peterhof (Yazlık Saray)",ru:"Петергоф"},desc:{tr:"'Rusya'nın Versailles'ı'. Yüzlerce altın fıskiyesiyle ünlüdür.",ru:"«Русский Версаль». Сотни золотых фонтанов."},why:{tr:["Altın fıskiyeler","Saray & bahçeler","Deniz kıyısı"],ru:["Золотые фонтаны","Дворец и сады","Берег залива"]}},
  {cat:"park",x:560,y:470,lat:59.7161,lng:30.3956,imgs:P.tsarskoe,metro:{tr:"(Şehir dışı — tren)",ru:"(За городом — электричка)"},time:"yarım gün",name:{tr:"Puşkin / Katerina Sarayı",ru:"Царское Село (Пушкин)"},desc:{tr:"Mavi-beyaz görkemli Katerina Sarayı ve ünlü 'Kehribar Odası'.",ru:"Екатерининский дворец и знаменитая Янтарная комната."},why:{tr:["Kehribar Odası","Görkemli saray","Geniş park"],ru:["Янтарная комната","Грандиозный дворец","Большой парк"]}},
  {cat:"museum",x:390,y:230,lat:59.9444,lng:30.3061,imgs:P.strelka,metro:{tr:"Vasileostrovskaya",ru:"Василеостровская"},time:"1 s",name:{tr:"Vasilyevski Adası Oku",ru:"Стрелка Васильевского острова"},desc:{tr:"Nehrin ikiye ayrıldığı tarihi meydan. Kırmızı Rostral Sütunlar.",ru:"Историческая площадь у разделения реки. Красные Ростральные колонны."},why:{tr:["En iyi panorama","Tarihi sütunlar","Gün batımı noktası"],ru:["Лучшая панорама","Исторические колонны","Точка для заката"]}},
  {cat:"must",x:430,y:215,lat:59.9417,lng:30.3083,imgs:P.bridges,metro:{tr:"Admiralteyskaya",ru:"Адмиралтейская"},time:"gece",name:{tr:"Açılan Köprüler (Geceleri)",ru:"Разводные мосты (ночью)"},desc:{tr:"Yaz gecelerinde Neva üzerindeki köprüler gemiler için açılır.",ru:"Летними ночами мосты над Невой разводят для судов."},why:{tr:["Eşsiz gece gösterisi","Beyaz geceler","Romantik atmosfer"],ru:["Уникальное ночное зрелище","Белые ночи","Романтика"]}}
  ],
  food:[
  {cat:"food",x:610,y:300,lat:59.9352,lng:30.3289,imgs:P.food_palkin,metro:{tr:"Nevsky Prospekt",ru:"Невский проспект"},price:{tr:"≈ 4000–6000 ₽",ru:"≈ 4000–6000 ₽"},name:{tr:"Palkinъ",ru:"Палкинъ"},desc:{tr:"1874'ten beri Nevski'nin köşesinde imparatorluk ihtişamına sahip efsanevi restoran.",ru:"Легендарный ресторан с 1874 года. Императорская роскошь."},why:{tr:["150 yıllık tarih","İmparatorluk ihtişamı","Klasik Rus mutfağı"],ru:["150 лет истории","Императорская роскошь","Классическая русская кухня"]}},
  {cat:"food",x:560,y:400,lat:59.9311,lng:30.3522,imgs:P.food_orangerie,metro:{tr:"Mayakovskaya",ru:"Маяковская"},price:{tr:"≈ 2500 ₽",ru:"≈ 2500 ₽"},name:{tr:"Saray Bahçesinde Çikolata-Limonluk",ru:"Шоколатерия-оранжерея в саду"},desc:{tr:"Bir sarayın kapalı bahçesinde gizlenmiş çikolatacı-limonluk.",ru:"Шоколатерия в закрытом саду дворца."},why:{tr:["Gizli saray bahçesi","El yapımı çikolata","Eşsiz atmosfer"],ru:["Тайный дворцовый сад","Шоколад ручной работы","Уникальная атмосфера"]}},
  {cat:"food",x:290,y:330,lat:59.9290,lng:30.2960,imgs:P.food_leth,metro:{tr:"Zvenigorodskaya",ru:"Звенигородская"},price:{tr:"≈ 1500–2500 ₽",ru:"≈ 1500–2500 ₽"},name:{tr:"Leth (Duyusal Mutfak)",ru:"Leth (Сенсорная кухня)"},desc:{tr:"Fontanka Nehri kıyısında avangard restoran. Yemekler aromalar, sesler ve görsellerle sunulur.",ru:"Авангардный ресторан на набережной Фонтанки. Блюда сопровождаются ароматами и звуками."},why:{tr:["Eşsiz duyusal deneyim","Nehir manzarası","Yaratıcı sunum"],ru:["Уникальный сенсорный опыт","Вид на реку","Креативная подача"]}}
 ]}
};
